### ISSUE TITLE
!python age_lsgan_transfer.py

### ISSUE THREAD

**Issue by Beekam-G** [dawei6875797/Face-Aging-with-Identity-Preserved-Conditional-Generative-Adversarial-Networks#30]
Traceback (most recent call last):
  File "age_lsgan_transfer.py", line 74, in <module>
    z_dim=FLAGS.noise_dim, scale_size=(FLAGS.image_size, FLAGS.image_size), mode='train')
  File "./tools/data_generator.py", line 54, in __init__
    self.read_class_list(self.class_lists)
  File "./tools/data_generator.py", line 110, in read_class_list
    f = open(self.file_folder + class_lists[i], 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/new_disk2/wangzw/tangxu/age_data/train_data/train_age_group_0.txt'

**Comment by BryceAYu** [comment]
已收到，会及时处理~
