### ISSUE TITLE
python age_lsgan_transfer.py

### ISSUE THREAD

**Issue by tilahun12** [dawei6875797/Face-Aging-with-Identity-Preserved-Conditional-Generative-Adversarial-Networks#31]
Traceback (most recent call last):
  File "age_lsgan_transfer.py", line 167, in <module>
    tf.compat.v1.app.run()
  File "/home/cv-lab/anaconda3/envs/Beekam/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/cv-lab/anaconda3/envs/Beekam/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/cv-lab/anaconda3/envs/Beekam/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "age_lsgan_transfer.py", line 163, in main
    my_train()
  File "age_lsgan_transfer.py", line 88, in my_train
    source_img_227, source_img_128, face_label = load_source_batch3(FLAGS.source_file, FLAGS.root_folder, FLAGS.batch_size)
  File "/home/cv-lab/Face-Aging-with-Identity-Preserved-Conditional-Generative-Adversarial-Networks-master/tools/source_input.py", line 128, in load_source_batch3
    img_list, label_list = get_imgAndlabel_list2(filename, img_folder)
  File "/home/cv-lab/Face-Aging-with-Identity-Preserved-Conditional-Generative-Adversarial-Networks-master/tools/source_input.py", line 173, in get_imgAndlabel_list2
    f = open(filename, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'your training file'

**Comment by BryceAYu** [comment]
已收到，会及时处理~

**Comment by AOguo21** [comment]
Have you solved this problem?

**Comment by BryceAYu** [comment]
已收到，会及时处理~

**Comment by AOguo21** [comment]
> 回溯（最近一次调用）：文件 “age_lsgan_transfer.py”，第 167 行，在 tf.compat.v1.app.run（） 中 文件 “/home/cv-lab/anaconda3/envs/Beekam/lib/python3.7/site-packages/tensorflow/python/platform/app.py”，第 40 行，在 run _run（main=main， argv=argv， flags_parser=_parse_flags_tolerate_undef） 文件 “/home/cv-lab/anaconda3/envs/Beekam/lib/python3.7/site-packages/absl/app.py”，第 312 行，在 run _run_main（main， args） 文件 “/home/cv-lab/anaconda3/envs/Beekam/lib/python3.7/site-packages/absl/app.py”，第 258 行，在 _run_main sys.exit（main（argv）） 文件中 文件 “age_lsgan_transfer.py”，第 163 行，在 main my_train（） 中 文件 “age_lsgan_transfer.py”，第 88 行，在 my_train source_img_227， source_img_128， face_label = load_source_batch3（FLAGS.source_file， FLAGS.root_folder， FLAGS.batch_size）文件“/home/cv-lab/Face-Aging-with-Identity-Preserve -Conditional-Generative-Adversarial-Networks-master/tools/source_input.py”，第 128 行，load_source_batch3 img_list，label_list = get_imgAndlabel_list2（文件名，img_folder） 文件 “/home/cv-lab/Face-Aging-with-Identity-Preserve - Conditional-Generative-Adversarial-Networks-master/tools/source_input.py”，第 173 行，get_imgAndlabel_list2 f = open（文件名，'r'）FileNotFoundError： [Errno 2] 没有这样的文件或目录：“您的训练文件”

Have you solved this problem?
